# Generated by Django 5.0.2 on 2024-02-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('domain', models.CharField(max_length=500)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=500)),
                ('size', models.IntegerField()),
                ('locality', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=500)),
                ('current_employees', models.IntegerField()),
                ('total_employee', models.IntegerField()),
            ],
        ),
    ]
